services:
  hub:
    image: ghcr.io/marwen1337/stati
    ports:
      - 8080:8080
    volumes:
      - db:/app/data
    environment:
      - MODE=service
  agent:
    image: ghcr.io/marwen1337/stati
    environment:
      - MODE=agent
      - AGENT_ACCESSKEY=undefined
      - AGENT_SERVER_HOST=host.docker.internal
      - AGENT_SERVER_PORT=8080

volumes:
  db:
